table salesorders
	lineageTag: 20035cd0-dedf-4d0d-bd8f-3146890e4f7e
	sourceLineageTag: [dbo].[salesorders]

	measure Qty = SUM(salesorders[Quantity])
		formatString: #,0
		lineageTag: afc12fca-1a90-4aa1-bedc-4cf7cc365c40

		changedProperty = Name

		changedProperty = FormatString

	column SalesOrderNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9c2c8ab5-b944-4f3e-86a8-02c361ecfb89
		sourceLineageTag: SalesOrderNumber
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ed6e8a5f-2dda-4fc5-a3ae-c65e98ec9083
		sourceLineageTag: SalesOrderLineNumber
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 8fe3f759-6bbf-455d-abaf-e0971ff45518
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b2882ea9-0e20-4b96-b931-cdf68a7d5d2b
		sourceLineageTag: CustomerName
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 79d6b5d3-7724-4793-9195-1ed0ba382f68
		sourceLineageTag: Email
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 01cf7a26-9d87-45ed-a658-e2dcb735758a
		sourceLineageTag: Item
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ffda0ea1-d6c5-4647-b4c2-532917460036
		sourceLineageTag: Quantity
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		sourceProviderType: real
		lineageTag: 9c2e9a5d-2f78-4ae4-9d88-4b99731f34e1
		sourceLineageTag: UnitPrice
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tax
		dataType: double
		sourceProviderType: real
		lineageTag: c8d6e44b-979e-4676-add4-7b2ce622bbb8
		sourceLineageTag: Tax
		summarizeBy: sum
		sourceColumn: Tax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition salesorders = entity
		mode: directLake
		source
			entityName: salesorders
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

